blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://zeitpal.com/faq
    about: Frequently Asked Questions
  - name: Contact US
    url: https://zeitpal.com/contact
    about: Have questions? We're happy to help.
